### ISSUE TITLE
Problem in unserializing DateTime in HHVM 

### ISSUE THREAD

**Issue by farizluqman** [desarrolla2/Cache#37]
I have detected a problem in serializing and unserializing DateTime in HHVM:

```
Error: exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/desarrolla2/cache/src/Adapter/AbstractAdapter.php:92 
Stack trace: #0 (): DateTime->__wakeup() 
#1 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/desarrolla2/cache/src/Adapter/AbstractAdapter.php(92): unserialize() 
#2 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/desarrolla2/cache/src/Adapter/File.php(153): Desarrolla2\Cache\Adapter\AbstractAdapter->unPack() 
#3 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/desarrolla2/cache/src/Adapter/File.php(63): Desarrolla2\Cache\Adapter\File->getValueFromCache() 
#4 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/desarrolla2/cache/src/Cache.php(57): Desarrolla2\Cache\Adapter\File->get() 
#5 /Applications/MAMP/htdocs/Rai-DigitalOcean/app/Service/Product/ProductService.php(142): Desarrolla2\Cache\Cache->get() 
#6 /Applications/MAMP/htdocs/Rai-DigitalOcean/resources/views/admin/products.php(8): Service\Product\ProductService->getAllProducts() 
#7 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/damnstupidsimple/core/src/Viewer.php(107): include() 
#8 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/damnstupidsimple/core/src/Viewer.php(75): Core\Viewer::render() 
#9 /Applications/MAMP/htdocs/Rai-DigitalOcean/app/Controller/Admin.php(41): Core\Viewer::file() 
#10 (): Controller\Admin->displayAnyPage() 
#11 /Applications/MAMP/htdocs/Rai-DigitalOcean/vendor/damnstupidsimple/core/src/Router.php(818): call_user_func_array() 
#12 /Applications/MAMP/htdocs/Rai-DigitalOcean/app/bootstrap.php(130): Core\Router::dispatch() 
#13 /Applications/MAMP/htdocs/Rai-DigitalOcean/index.php(56): include() 
#14 {main}
```

Issue: https://github.com/facebook/hhvm/issues/6783

## Reproducing Error:
```php
$cache =  new Cache($adapter);
$time =  \DateTime::createFromFormat('U', time());
$cache->set('time', $time, 3600);
$cache->get('time'); // error here when unserializing the DateTime object
```

My workaround now is to use NotCache at the current time.

**Comment by jasny** [comment]
Please provide a PR.
_Note that HHVM is not officially supported by this library._

**Comment by desarrolla2** [comment]
@farizluqman maybe you need to configure time zone in your environemnt?
